### ISSUE TITLE
How to use ?

### ISSUE THREAD

**Issue by UNI49** [nitsan-technologies/ns_lazy_load#1]
Hi, I need some help to use this extension.

I've installed it and I've added is Typoscript in ***Include static (from extensions)*** (in root template section). But nothing happened.

How to do? Is a special configuration needed?

Thanks for help.

**Comment by nitsan-technologies** [comment]
Hi @UNI49 

Thank you for your message, The lasy_load mechanism work base on the class **lazy.** We have taken the image template in our extension to add that class in the Image(img) tag.

If you have changed the default **TYPO3 core image templating**, then you need to add a **lazy** class in your **custom templating.**

**Note:** Please add a class in Image(img) tag.

**Example**
**Image tag:** http://i.imgur.com/ECSNHSK.png
**Implementation verification:** http://i.imgur.com/dDp8daF.png

Please check and let us know if you require further help on this point.

Thank you!

**Comment by UNI49** [comment]
Thanks for your explanation .

So your extension only works for CType **Text & Images**, **Text & Media** and **Images**?
It doesn't override *fluid* (f:image/f:media) ?

Maybe it'll be a better idea to override **f:**, isn't it?

Thanks again for help.

**Comment by UNI49** [comment]
Thanks for help.

It's definitely a good things to do.
