### ISSUE TITLE
Plugin does not work as it should

### ISSUE THREAD

**Issue by haug-den-lucas** [nitsan-technologies/ns_lazy_load#2]
Hello,

I don't think the application works as it should.

## How to reproduce
1. Clear your browsers cache
2. Open Developer Tools
3. Use the mobile device screen simulator in your developer tools to reduce your screen width.
4. Open the testwebsite, don't scroll down: https://demo.t3terminal.com/t3t-extensions/lazy-load/
5. Now use the bandwidth simulator in your developer tools to reduce your bandwidth to the minimum still connected value
6. Quickly scroll down, you will see the pictures are already loaded, even though lazyload says they are only loaded now.

Another way to confirm it is to execute steps 1 to 4 and then go to the "Sources" Tab in developer tools and see all pictures are already loaded.

## Why does it happen
Problem is, that normally lazyloading libraries require to remove the `src` attribute from image tags and only use the `data-src` attribute. But here in Typo3 the `src` attribute is still existing, so the browser will load the pictures anyway

Is this a known issue?

**Comment by nitsan-technologies** [comment]
Hello @Ich5003 

First of all, thank you to use this extension.

Yes, now data-src added in image tag and removed src tag. So, Now lazyLoading is working fine.


Thanks again & Regards.
